FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app1.py app2.py ./

FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=0 /app/app1.py /app/app2.py /app/

CMD ["nginx", "-g", "daemon off;"]
